# Interaction id
int8 id

# Perceived size of the object (O);
# possible values: 0=not perceived in this interaction, 1=small, 2=big
int8 object_size

# Perceived human head and eyes movements (HA);
# possible values: 0=not perceived in this interaction, 1=looking at the robot face, 2=looking at the toy, 3=looking away
int8 human_action

# Perceived human facial expressions (HE);
# possible values: 0=not perceived in this interaction, 1=happy, 2=sad, 3=neutral
int8 human_expression
